### ISSUE TITLE
Segfault after selecting a directory

### ISSUE THREAD

**Issue by Hion-V** [MAJigsaw77/hxnativefiledialog#1]
As the title suggests I'm running into a segfault after selecting a directory as per the example source provided in this repository on Ubuntu 22.04 and haxe 4.3.3.
![Screenshot from 2024-02-20 07-06-09](https://github.com/MAJigsaw77/hxnativefiledialog/assets/6537945/0f220f67-a4f9-4ed0-acb2-14efef97839b)

**Comment by MAJigsaw77** [comment]
I need to update the samples a bit so they won't do that (they kinda need to have threads added).

**Comment by MAJigsaw77** [comment]
Try with the current samples
